// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mdt_dialout.proto
#ifndef GRPC_mdt_5fdialout_2eproto__INCLUDED
#define GRPC_mdt_5fdialout_2eproto__INCLUDED

#include "mdt_dialout.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace mdt_dialout {

class gRPCMdtDialout final {
 public:
  static constexpr char const* service_full_name() {
    return "mdt_dialout.gRPCMdtDialout";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // rpc MdtDialout(stream MdtDialoutArgs) returns(stream MdtDialoutArgs) {};
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>> MdtDialoutGpbkv(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>>(MdtDialoutGpbkvRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>> AsyncMdtDialoutGpbkv(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>>(AsyncMdtDialoutGpbkvRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>> PrepareAsyncMdtDialoutGpbkv(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>>(PrepareAsyncMdtDialoutGpbkvRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // rpc MdtDialout(stream MdtDialoutArgs) returns(stream MdtDialoutArgs) {};
      virtual void MdtDialoutGpbkv(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mdt_dialout::Telemetry,::mdt_dialout::Telemetry>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* MdtDialoutGpbkvRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* AsyncMdtDialoutGpbkvRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* PrepareAsyncMdtDialoutGpbkvRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>> MdtDialoutGpbkv(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>>(MdtDialoutGpbkvRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>> AsyncMdtDialoutGpbkv(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>>(AsyncMdtDialoutGpbkvRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>> PrepareAsyncMdtDialoutGpbkv(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>>(PrepareAsyncMdtDialoutGpbkvRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void MdtDialoutGpbkv(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mdt_dialout::Telemetry,::mdt_dialout::Telemetry>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* MdtDialoutGpbkvRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* AsyncMdtDialoutGpbkvRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* PrepareAsyncMdtDialoutGpbkvRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MdtDialoutGpbkv_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // rpc MdtDialout(stream MdtDialoutArgs) returns(stream MdtDialoutArgs) {};
    virtual ::grpc::Status MdtDialoutGpbkv(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_MdtDialoutGpbkv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MdtDialoutGpbkv() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MdtDialoutGpbkv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MdtDialoutGpbkv(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMdtDialoutGpbkv(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MdtDialoutGpbkv<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_MdtDialoutGpbkv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MdtDialoutGpbkv() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->MdtDialoutGpbkv(context); }));
    }
    ~WithCallbackMethod_MdtDialoutGpbkv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MdtDialoutGpbkv(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* MdtDialoutGpbkv(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_MdtDialoutGpbkv<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MdtDialoutGpbkv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MdtDialoutGpbkv() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MdtDialoutGpbkv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MdtDialoutGpbkv(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MdtDialoutGpbkv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MdtDialoutGpbkv() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MdtDialoutGpbkv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MdtDialoutGpbkv(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMdtDialoutGpbkv(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MdtDialoutGpbkv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MdtDialoutGpbkv() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->MdtDialoutGpbkv(context); }));
    }
    ~WithRawCallbackMethod_MdtDialoutGpbkv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MdtDialoutGpbkv(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mdt_dialout::Telemetry, ::mdt_dialout::Telemetry>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* MdtDialoutGpbkv(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace mdt_dialout


#endif  // GRPC_mdt_5fdialout_2eproto__INCLUDED
