// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei_dialout.proto

#include "huawei_dialout.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace huawei_dialout {
constexpr serviceArgs::serviceArgs(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : errors_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , reqid_(int64_t{0})
  , _oneof_case_{}{}
struct serviceArgsDefaultTypeInternal {
  constexpr serviceArgsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~serviceArgsDefaultTypeInternal() {}
  union {
    serviceArgs _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT serviceArgsDefaultTypeInternal _serviceArgs_default_instance_;
}  // namespace huawei_dialout
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_huawei_5fdialout_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_huawei_5fdialout_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_huawei_5fdialout_2eproto = nullptr;

const uint32_t TableStruct_huawei_5fdialout_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::huawei_dialout::serviceArgs, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::huawei_dialout::serviceArgs, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::huawei_dialout::serviceArgs, reqid_),
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::huawei_dialout::serviceArgs, errors_),
  PROTOBUF_FIELD_OFFSET(::huawei_dialout::serviceArgs, MessageData_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::huawei_dialout::serviceArgs)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::huawei_dialout::_serviceArgs_default_instance_),
};

const char descriptor_table_protodef_huawei_5fdialout_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024huawei_dialout.proto\022\016huawei_dialout\"`"
  "\n\013serviceArgs\022\r\n\005ReqId\030\001 \001(\003\022\016\n\004data\030\002 \001"
  "(\014H\000\022\023\n\tdata_json\030\004 \001(\tH\000\022\016\n\006errors\030\003 \001("
  "\tB\r\n\013MessageData2`\n\017gRPCDataservice\022M\n\013d"
  "ataPublish\022\033.huawei_dialout.serviceArgs\032"
  "\033.huawei_dialout.serviceArgs\"\000(\0010\001b\006prot"
  "o3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_huawei_5fdialout_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_huawei_5fdialout_2eproto = {
  false, false, 242, descriptor_table_protodef_huawei_5fdialout_2eproto, "huawei_dialout.proto", 
  &descriptor_table_huawei_5fdialout_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_huawei_5fdialout_2eproto::offsets,
  file_level_metadata_huawei_5fdialout_2eproto, file_level_enum_descriptors_huawei_5fdialout_2eproto, file_level_service_descriptors_huawei_5fdialout_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_huawei_5fdialout_2eproto_getter() {
  return &descriptor_table_huawei_5fdialout_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_huawei_5fdialout_2eproto(&descriptor_table_huawei_5fdialout_2eproto);
namespace huawei_dialout {

// ===================================================================

class serviceArgs::_Internal {
 public:
};

serviceArgs::serviceArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:huawei_dialout.serviceArgs)
}
serviceArgs::serviceArgs(const serviceArgs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  errors_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    errors_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_errors().empty()) {
    errors_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_errors(), 
      GetArenaForAllocation());
  }
  reqid_ = from.reqid_;
  clear_has_MessageData();
  switch (from.MessageData_case()) {
    case kData: {
      _internal_set_data(from._internal_data());
      break;
    }
    case kDataJson: {
      _internal_set_data_json(from._internal_data_json());
      break;
    }
    case MESSAGEDATA_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:huawei_dialout.serviceArgs)
}

inline void serviceArgs::SharedCtor() {
errors_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  errors_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
reqid_ = int64_t{0};
clear_has_MessageData();
}

serviceArgs::~serviceArgs() {
  // @@protoc_insertion_point(destructor:huawei_dialout.serviceArgs)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void serviceArgs::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  errors_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (has_MessageData()) {
    clear_MessageData();
  }
}

void serviceArgs::ArenaDtor(void* object) {
  serviceArgs* _this = reinterpret_cast< serviceArgs* >(object);
  (void)_this;
}
void serviceArgs::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void serviceArgs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void serviceArgs::clear_MessageData() {
// @@protoc_insertion_point(one_of_clear_start:huawei_dialout.serviceArgs)
  switch (MessageData_case()) {
    case kData: {
      MessageData_.data_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
      break;
    }
    case kDataJson: {
      MessageData_.data_json_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
      break;
    }
    case MESSAGEDATA_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = MESSAGEDATA_NOT_SET;
}


void serviceArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:huawei_dialout.serviceArgs)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  errors_.ClearToEmpty();
  reqid_ = int64_t{0};
  clear_MessageData();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* serviceArgs::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 ReqId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          reqid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_data();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string errors = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_errors();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "huawei_dialout.serviceArgs.errors"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string data_json = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_data_json();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "huawei_dialout.serviceArgs.data_json"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* serviceArgs::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:huawei_dialout.serviceArgs)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 ReqId = 1;
  if (this->_internal_reqid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_reqid(), target);
  }

  // bytes data = 2;
  if (_internal_has_data()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_data(), target);
  }

  // string errors = 3;
  if (!this->_internal_errors().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_errors().data(), static_cast<int>(this->_internal_errors().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "huawei_dialout.serviceArgs.errors");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_errors(), target);
  }

  // string data_json = 4;
  if (_internal_has_data_json()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_data_json().data(), static_cast<int>(this->_internal_data_json().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "huawei_dialout.serviceArgs.data_json");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_data_json(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:huawei_dialout.serviceArgs)
  return target;
}

size_t serviceArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:huawei_dialout.serviceArgs)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string errors = 3;
  if (!this->_internal_errors().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_errors());
  }

  // int64 ReqId = 1;
  if (this->_internal_reqid() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_reqid());
  }

  switch (MessageData_case()) {
    // bytes data = 2;
    case kData: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_data());
      break;
    }
    // string data_json = 4;
    case kDataJson: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_data_json());
      break;
    }
    case MESSAGEDATA_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData serviceArgs::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    serviceArgs::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*serviceArgs::GetClassData() const { return &_class_data_; }

void serviceArgs::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<serviceArgs *>(to)->MergeFrom(
      static_cast<const serviceArgs &>(from));
}


void serviceArgs::MergeFrom(const serviceArgs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:huawei_dialout.serviceArgs)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_errors().empty()) {
    _internal_set_errors(from._internal_errors());
  }
  if (from._internal_reqid() != 0) {
    _internal_set_reqid(from._internal_reqid());
  }
  switch (from.MessageData_case()) {
    case kData: {
      _internal_set_data(from._internal_data());
      break;
    }
    case kDataJson: {
      _internal_set_data_json(from._internal_data_json());
      break;
    }
    case MESSAGEDATA_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void serviceArgs::CopyFrom(const serviceArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:huawei_dialout.serviceArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool serviceArgs::IsInitialized() const {
  return true;
}

void serviceArgs::InternalSwap(serviceArgs* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &errors_, lhs_arena,
      &other->errors_, rhs_arena
  );
  swap(reqid_, other->reqid_);
  swap(MessageData_, other->MessageData_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata serviceArgs::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_huawei_5fdialout_2eproto_getter, &descriptor_table_huawei_5fdialout_2eproto_once,
      file_level_metadata_huawei_5fdialout_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace huawei_dialout
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::huawei_dialout::serviceArgs* Arena::CreateMaybeMessage< ::huawei_dialout::serviceArgs >(Arena* arena) {
  return Arena::CreateMessageInternal< ::huawei_dialout::serviceArgs >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
