// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: huawei_dialout.proto
#ifndef GRPC_huawei_5fdialout_2eproto__INCLUDED
#define GRPC_huawei_5fdialout_2eproto__INCLUDED

#include "huawei_dialout.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace huawei_dialout {

class gRPCDataservice final {
 public:
  static constexpr char const* service_full_name() {
    return "huawei_dialout.gRPCDataservice";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>> dataPublish(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>>(dataPublishRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>> AsyncdataPublish(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>>(AsyncdataPublishRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>> PrepareAsyncdataPublish(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>>(PrepareAsyncdataPublishRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void dataPublish(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::huawei_dialout::serviceArgs,::huawei_dialout::serviceArgs>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* dataPublishRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* AsyncdataPublishRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* PrepareAsyncdataPublishRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>> dataPublish(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>>(dataPublishRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>> AsyncdataPublish(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>>(AsyncdataPublishRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>> PrepareAsyncdataPublish(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>>(PrepareAsyncdataPublishRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void dataPublish(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::huawei_dialout::serviceArgs,::huawei_dialout::serviceArgs>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* dataPublishRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* AsyncdataPublishRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* PrepareAsyncdataPublishRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_dataPublish_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status dataPublish(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_dataPublish : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_dataPublish() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_dataPublish() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status dataPublish(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdataPublish(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_dataPublish<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_dataPublish : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_dataPublish() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->dataPublish(context); }));
    }
    ~WithCallbackMethod_dataPublish() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status dataPublish(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* dataPublish(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_dataPublish<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_dataPublish : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_dataPublish() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_dataPublish() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status dataPublish(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_dataPublish : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_dataPublish() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_dataPublish() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status dataPublish(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdataPublish(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_dataPublish : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_dataPublish() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->dataPublish(context); }));
    }
    ~WithRawCallbackMethod_dataPublish() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status dataPublish(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::huawei_dialout::serviceArgs, ::huawei_dialout::serviceArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* dataPublish(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace huawei_dialout


#endif  // GRPC_huawei_5fdialout_2eproto__INCLUDED
